Repository jimsalterjrs/sanoid, pull requests merged in 2019-03, with the labels that each got.

#357 added bwlimit units
  syncoid
Labels: ready to merge

#360 initial replication without intermediate snapshots should use the cre…
  syncoid
Labels: bugfix

#353 check if ssh connection works
  syncoid
Labels: bugfix, ready to merge

#348 fix unitialized variable
  syncoid
Labels: bugfix, ready to merge

#340 only list filesystems and volumes
  sanoid
Labels: bugfix, ready to merge

#335 Catch some errors
  syncoid
Labels: bugfix, ready to merge

#206 Add comprehensive installation instructions
  INSTALL
  INSTALL.md
Labels: ready to merge

#343 implemented parsing of provided zfs send/recv options and whitelisting for each use case as needed
  syncoid
Labels: enhancement

#319 removed debug output from excludes loop
  syncoid
Labels: bugfix, ready to merge

#334 check pool capability for resumeable replication instead of checking …
  syncoid
Labels: bugfix, ready to merge

#352 use ordinary replication if clone recreation fails
  syncoid
Labels: bugfix, ready to merge

#342 implemented creation of zfs bookmarks
  README.md
  syncoid
Labels: enhancement, ready to merge

#320 zfs recursion
  sanoid
Labels: enhancement, review needed

#367 Revert #365
  INSTALL.md
Labels: enhancement, ready to merge

#341 fix bookmark edge case where replication was already done to the late…
  syncoid
  tests/syncoid/4_bookmark_replication_edge_case/run.sh
Labels: bugfix, ready to merge

#270 don't use hardcoded paths
  syncoid
Labels: enhancement, review needed
