Repository jimsalterjrs/sanoid, pull requests merged in 2019-05, with the labels that each got.

#382 fixed ordering of snapshots with the same creation timestamp
  syncoid
Labels: review needed

#309 WIP: reset resume state
  syncoid
Labels: revision needed

#385 more error handling of zfs failures
  INSTALL.md
  packages/debian/control
  packages/gentoo/sys-fs/sanoid/Manifest
  packages/gentoo/sys-fs/sanoid/sanoid-2.0.1.ebuild
  packages/gentoo/sys-fs/sanoid/sanoid-9999.ebuild
  packages/rhel/sanoid.spec
  syncoid
  tests/syncoid/5_reset_resume_state/run.sh
  tests/syncoid/6_reset_resume_state2/run.sh
Labels: ready to merge

#362 Changed (and simplified) DST handling
  README.md
  sanoid
  tests/2_dst_handling/run.sh
Labels: ready to merge

#375 Declare that sanoid service 'Wants' sanoid-prune
  INSTALL.md
  packages/debian/sanoid-prune.service
  packages/debian/sanoid.service
Labels: ready to merge

#368 Added line to enable sanoid-prune.service
  INSTALL.md
Labels: ready to merge

#370 Update INSTALL.md
  INSTALL.md
  packages/debian/rules
Labels: ready to merge
