Repository jimsalterjrs/sanoid, pull requests merged in 2020-11, with the labels that each got.

#576 Update sanoid.conf
  sanoid.conf
Labels: ready to merge

#580 Update INSTALL.md
  INSTALL.md
Labels: ready to merge

#536 implemented option for keeping sync snaps
  README.md
  syncoid
Labels: enhancement, ready to merge

#510 catch another case in which the resume state isn't availabe anymore
  syncoid
Labels: enhancement, ready to merge

#529 use sudo if neccessary for checking pool capabilities regarding resum…
  syncoid
Labels: enhancement, ready to merge

#503 document the atomic way to take snapshots recursively
  sanoid.conf
Labels: ready to merge

#374 Do not require user to be specified for syncoid
  syncoid
Labels: ready to merge

#500 added cron setup example
  INSTALL.md
  README.md
Labels: ready to merge

#501 extended install instructions for centos if perl dependencies can't b…
  INSTALL.md
Labels: ready to merge

#502 fix typo in argument description
  README.md
Labels: ready to merge

#504 added note about capacity limit overriding
  sanoid.defaults.conf
Labels: ready to merge

#505 added note about the default options if some interval types aren't ...
  README.md
Labels: ready to merge

#507 fix iszfsbusy check for similar dataset names
  syncoid
Labels: bugfix, ready to merge

#508 check for an invalid argument combination
  syncoid
Labels: ready to merge

#509 added note for busybox based distributions
  INSTALL.md
Labels: ready to merge

#399 don't use hardcoded paths
  sanoid
Labels: enhancement, ready to merge

#498 append timezone offset to the syncoid snapshot name to fix DST collis…
  syncoid
Labels: bugfix

#497 Scripts snapshot grouping
  README.md
  sanoid
  sanoid.conf
  sanoid.defaults.conf
Labels: enhancement

#437 preserve recordsize
  README.md
  syncoid
  tests/syncoid/7_preserve_recordsize/run.sh
Labels: enhancement, review needed
