Repository jimsalterjrs/sanoid, pull requests merged in 2020-01, with the labels that each got.

#476 implemented fallback for listing snapshots on solaris
  syncoid
Labels: enhancement, ready to merge

#473 remove invalid locks caused by race conditions or else the block the …
  sanoid
Labels: bugfix, ready to merge

#472 Revert "Depend on systemd"
  packages/debian/control
Labels: packaging, ready to merge

#462 remove 's in monitoring messages
  sanoid
Labels: ready to merge

#383 Gracefully handle error when source dataset disappeared
  syncoid
Labels: enhancement, ready to merge

#415 added needed verbose flag for send size estimation (at least for late…
  syncoid
Labels: bugfix, ready to merge

#450 improve dataset detection by only including mounted datasets
  findoid
Labels: enhancement, ready to merge

#451 don't use hardcoded paths (findoid)
  findoid
Labels: enhancement, ready to merge

#452 handle FileNotFound errors properly
  findoid
Labels: bugfix, ready to merge

#453 also show current file version if available
  findoid
Labels: enhancement, ready to merge

#474 Update INSTALL.md
  INSTALL.md
Labels: enhancement, ready to merge

#408 add ability to configure pv in syncoid
  syncoid
Labels: enhancement, review needed

#478 fixed missing ;
  sanoid
Labels: ready to merge

#483 post install script for debian package to remove old unused snapshot …
  packages/debian/postinst
Labels: packaging, ready to merge

#481 Fixed Typo in arguments.
  syncoid
Labels: bugfix, ready to merge

#491 fix debian postinst in the case of non existing legacy cache file
  packages/debian/postinst
Labels: packaging, ready to merge
