Repository jimsalterjrs/sanoid, pull requests merged in 2023-03, with the labels that each got.

#766 bring back no-rollback option
  syncoid
Labels: enhancement, ready to merge

#767 fix snapshot listing fallback
  syncoid
Labels: ready to merge, bugfix

#768 improve accuracy of zfs receive check
  syncoid
Labels: enhancement

#769 syncoid should exit with an error if the specified src dataset doesn'…
  syncoid
Labels: ready to merge, bugfix

#775 Update README.md
  README.md
Labels: ready to merge

#605 implemented removal of conflicting snapshots with force-delete option
  README.md
  syncoid
  tests/syncoid/8_force_delete_snapshot/run.sh
Labels: enhancement, review needed

#606 fix duplicate key definitions by only using the first occurence and p…
  sanoid
Labels: ready to merge, bugfix

#608 don't try to parse stats for spares which are in use as there are none
  sanoid
Labels: ready to merge
