Repository jimsalterjrs/sanoid, pull requests merged in 2023-04, with the labels that each got.

#523 Add target snapshot deletion.
  README.md
  syncoid
Labels: enhancement, ready to merge

#808 fixes some tests which fail on fast storage
  tests/syncoid/5_reset_resume_state/run.sh
  tests/syncoid/6_reset_resume_state2/run.sh
Labels: ready to merge, bugfix

#809 support bookmarks which are taken in the same second
  syncoid
Labels: enhancement, ready to merge

#622 syncoid hold
  README.md
  syncoid
Labels: ready to merge

#819 fix default behaviour if run without providing arguments
  sanoid
Labels: ready to merge, bugfix

#513 implemented option for direct connection via socat and busybox nc
  README.md
  syncoid
Labels: review needed
