Repository jimsalterjrs/sanoid, pull requests merged in 2024-04, with the labels that each got.

#909 rename ssh control socket to avoid problem with length limits and con…
  syncoid
Labels: ready to merge, bugfix

#911 handle error output for filtered replications
  syncoid
Labels: ready to merge, bugfix

#903 fix(syncoid): regather $snaps on --delete-target-snapshots flag
  syncoid
Labels: ready to merge, bugfix

#904 test adaptions
  tests/run-tests.sh
  tests/syncoid/001_bookmark_replication_intermediate/run.sh
  tests/syncoid/002_bookmark_replication_no_intermediate/run.sh
  tests/syncoid/003_force_delete/run.sh
  tests/syncoid/004_bookmark_replication_edge_case/run.sh
  tests/syncoid/005_reset_resume_state/run.sh
  tests/syncoid/006_reset_resume_state2/run.sh
  tests/syncoid/007_preserve_recordsize/run.sh
  tests/syncoid/008_force_delete_snapshot/run.sh
  tests/syncoid/009_preserve_properties/run.sh
  tests/syncoid/010_filter_snaps/run.sh
  tests/syncoid/011_sync_out-of-order_snapshots/run.sh
  tests/syncoid/run-tests.sh
Labels: enhancement, ready to merge

#905 [findoid] support relative paths
  findoid
Labels: enhancement, ready to merge

#920 [sanoid] implemented dataset cache and fix race conditions
  sanoid
Labels: enhancement, bugfix
