Repository jimsalterjrs/sanoid, pull requests merged in 2024-01, with the labels that each got.

#699 Add --include-snaps and --exclude-snaps options to syncoid
  README.md
  syncoid
  tests/syncoid/10_filter_snaps/run.sh
Labels: enhancement, revision needed

#883 update possible zfs send options
  syncoid
Labels: ready to merge

#882 escape property key and value pair in case of property preservation
  syncoid
  tests/syncoid/9_preserve_properties/run.sh
Labels: bugfix

#881 prevent destroying of root dataset which leads to infinite loop
  syncoid
Labels: ready to merge, bugfix

#859 fix "creation"/"guid" regex detection
  syncoid
Labels: ready to merge, bugfix

#841 Update INSTALL.md
  INSTALL.md
Labels: ready to merge

#872 fix zfs-get for "--preserve-properties" and tests
  syncoid
  tests/syncoid/7_preserve_recordsize/run.sh
  tests/syncoid/9_preserve_properties/run.sh
Labels: ready to merge

#855 debian: add openzfs-zfsutils as an alternative to zfsutils-linux
  packages/debian/control
Labels: ready to merge

#843 Fix typos in syncoid documentation
  README.md
  syncoid
Labels: ready to merge

#856 Fixes jimsalterjrs/sanoid#851
  sanoid
Labels: ready to merge

#884 sanoid.conf: document two options for recursive
  sanoid.conf
Labels: ready to merge
